### ISSUE TITLE
What should be public API?

### ISSUE THREAD

**Issue by fonsp** [JuliaPluto/ExpressionExplorer.jl#1]
Maybe as little as possible?

But for the configuration system, I guess we need a lot to be public.

@Pangoraw

**Comment by pankgeorg** [comment]
Also cc @StefanKarpinski if you want to chime in!

**Comment by fonsp** [comment]
I made https://github.com/JuliaPluto/ExpressionExplorer.jl/pull/2, and I think `ReactiveNode` is easier to use than the raw `SymbolsState` result from ExpressionExplorer. So maybe that should be the API. (In Pluto, we only use `ReactiveNode`.)

We could also add useful functions on top of this, like a function `depends_on(a::ReactiveNode, b::ReactiveNode)::Bool`, or include our reactive sorting algorithm.

**Comment by fonsp** [comment]
More progress in https://github.com/JuliaPluto/ExpressionExplorer.jl/pull/3, check out the new README

**Comment by Pangoraw** [comment]
+1 for ReactiveNode. It would be interesting to see if we can get more finegrained variable locations such as scopes and ranges as in scopestate_statefield.js using JuliaSyntax.jl.

**Comment by fonsp** [comment]
Nice! Let's do that in the 2.0.0 release? :) Now that it's a separate package it might also be easier for the Julia community to contribute to that.
