### ISSUE TITLE
Remove Markdown dependency

### ISSUE THREAD

**Issue by Pangoraw** [JuliaPluto/ExpressionExplorer.jl#8]
the list of macro seems a bit arbitrary for users:

https://github.com/JuliaPluto/ExpressionExplorer.jl/blob/5766ad187fc2d812d21e0fdac4604eebacf2a77c/src/explore.jl#L1034-L1040

Maybe provide a way for configurations to provide with defaults:

```julia
ExpressionExplore.can_macroexpand(::AbstractExpressionExplorerConfiguration, e::Union{Expr,Symbol}) = false
ExpressionExplore.macroexpand_module(::AbstractExpressionExplorerConfiguration) = MacroExpandInHere
```

**Comment by fonsp** [comment]
Maybe users (including Pluto) should first macroexpand what they want, and then call ExpressionExplorer on the result? Then EE never needs to expand, and we don't need the `AbstractExpressionExplorerConfiguration` anymore?
